name: HelloWorldApp
options:
  bundleIdPrefix: io.github.a1mohamad
targets:
  HelloWorldApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Sources/HelloWorldApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.a1mohamad.helloworldapp
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        CODE_SIGN_STYLE: Automatic
